plugins {
    id 'java'
    id 'application'
    //Download the official JavaFX libraries
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

//group = 'com.comp3220_group5'
version = '1.0-SNAPSHOT'

//Automatically download external libraries from mavenCentral
repositories {
    mavenCentral()
}

// Configure JavaFX modules and version
javafx {
    version = '21'
    modules = ['javafx.controls', 'javafx.fxml']
}

dependencies {
    // SQLite JDBC Driver
    implementation 'org.xerial:sqlite-jdbc:3.45.1.0'
    
    // Testing dependencies
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

// Main application class
application {
    mainClass = 'Main' 
}

tasks.named('test') {
    useJUnitPlatform()
}